### PR TITLE
added volunteer button

### PR DESCRIPTION
**Pull request by swaaz**
image
image

### CODE REVIEW

**Comment by ionicc** [comment]
@swaaz Make em stack horizontally on Desktop

**Comment by swaaz** [comment]
> @swaaz Make em stack horizontally on Desktop

isn't it against the design of our page? because other buttons are placed below. if it is fine then I can do it now.

**Comment by ionicc** [comment]
@swaaz Makes sense

**Review by ionicc — APPROVED** [review]
lgttm

**Pull request merged**
