### PR TITLE
devfolio key addition

### PR DESCRIPTION
**Pull request by Aniket-Mishra**

### CODE REVIEW

**Comment by ionicc** [comment]
@Aniket-Mishra 🤣 You didn't change the href tho

**Comment by ionicc** [comment]
https://github.com/codezoned/codezoned.github.io/blob/90c93862c12cbba5b7ead70bf148434533b33aea/index.html#L335

**Comment by Aniket-Mishra** [comment]
> @Aniket-Mishra 🤣 You didn't change the href tho

My bad my bad xD I'll fix that

**Comment by Aniket-Mishra** [comment]
Closing the PR because the link is much better. Going to the devfolio site looks better than being redirected to the form directly.

**Pull request closed without merging**
