### PR TITLE
Fixed Discord Button

### LINKED ISSUE #17: Devfolio Button
Add the Devfolio logic to the button when it's provided.

### PR DESCRIPTION
**Pull request by swaaz**
image
image
image
image
image

### CODE REVIEW

**Comment by swaaz** [comment]
image
image

**Comment by swaaz** [comment]
closing: #17

**Comment by Aniket-Mishra** [comment]
The button is not fixed for larger screens : 
problem

**Comment by Aniket-Mishra** [comment]
The bigger the screens get, the further away the buttons go from the center. Try to left align them after a certain screen width using @media queries for 3500+ sizes.

**Comment by swaaz** [comment]
@Aniket-Mishra @ionicc Finally Fixed the buttons and speaker
image
image
image
image

**Comment by swaaz** [comment]
closing: #31

**Comment by Aniket-Mishra** [comment]
> @Aniket-Mishra @ionicc Finally Fixed the buttons and speaker
> image
> image
> image
> image

That's great work! I have added links to Arka and Zafeer's profiles and added targets to the links. Should be good to merge.
@ionicc Check it once. 
Cheers,
Aniket

**Comment by swaaz** [comment]
@ionicc Everything looks good so after verifying you can merge

**Comment by swaaz** [comment]
@ionicc I aligned abhi jain to left if width is more than 1600px so that next when we add new speaker it will be easy
image
image

**Comment by swaaz** [comment]
Added new speaker
image
image

**Review by ionicc — APPROVED** [review]
LGGGGTM

**Pull request merged**
