### PR TITLE
Speaker and Sponsors Added

### PR DESCRIPTION
**Pull request by swaaz**
## Changes
- Added New Speaker
- Added new Sponsors under Gold and Bronze
- Added logo and Speaker image in the folder
## Mobile View
image
image
image
## Desktop View
image
image
image

### CODE REVIEW

**Comment by swaaz** [comment]
This Pull Requested can be merged because I fixed that bug @Aniket-Mishra

**Review by ionicc — APPROVED** [review]
Alt Text

**Comment by swaaz** [comment]
@ionicc  Removed bg of Walfram
image

**Review by ionicc — APPROVED** [review]

**Comment by Aniket-Mishra** [comment]
The Wolfram Language and the EchoAR logos seem to be too close to the ones above them. We'll need a little bit of spacing. And on certain phones we need to make Sagar's card bigger in the speaker section. We have not yet added Kevin's picture, gotta add that too.

**Pull request merged**
